title: Eutopia
description: Serveur Vintage Story francophone.
lang: fr
url: "https://owenjuniusbrutus.github.io"
baseurl: ""
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - output
  - vendor
